Add Implementation page
globalprivacycontrol/landing-page pull request #33
Opened 2022-09-09 22:51 UTC by dharb

This PR adds an implementation page (and pdf) to provide publishers with better guidance on how to implement GPC.

2022-09-09 23:16 UTC, dharb commented
Hey @AramZS @SebastianZimmeck @pdolanjski, this is ready to go. Any chance one of you could build this locally and take a quick look at the changes to make sure everything looks right before I merge?

2022-09-13 01:49 UTC, SebastianZimmeck requested changes
Great! Two minor suggestions.

1. Add "Assistant Professor of Computer Science" for me.
2. Add "emphasis added" to the quote on the site just like in the pdf.

2022-09-14 15:39 UTC, dharb commented
Thanks @SebastianZimmeck, updated.

2022-09-14 16:10 UTC, SebastianZimmeck approved these changes

2022-09-14 18:17 UTC, merged